import type { Student, StudentKPIs, Alert, InterventionPlan } from "@/lib/types/dashboard"

export const mockStudents: Student[] = [
  {
    id: "stu_001",
    name: "Martín González",
    age: 9,
    grade: "4to grado",
    mode: "child",
    avatar: "/images/lex.png",
    parentIds: ["parent_001"],
    teacherIds: ["teacher_001"],
    psychopedagogistId: "psych_001",
    enrolledAt: "2025-01-15",
  },
  {
    id: "stu_002",
    name: "Sofía Ramírez",
    age: 14,
    grade: "2do año",
    mode: "teen",
    parentIds: ["parent_002"],
    teacherIds: ["teacher_001"],
    psychopedagogistId: "psych_001",
    enrolledAt: "2025-02-01",
  },
  {
    id: "stu_003",
    name: "Lucas Fernández",
    age: 10,
    grade: "5to grado",
    mode: "child",
    parentIds: ["parent_003"],
    teacherIds: ["teacher_001"],
    psychopedagogistId: "psych_001",
    enrolledAt: "2025-01-20",
  },
  {
    id: "stu_004",
    name: "Valentina López",
    age: 13,
    grade: "1er año",
    mode: "teen",
    parentIds: ["parent_004"],
    teacherIds: ["teacher_001"],
    psychopedagogistId: "psych_001",
    enrolledAt: "2025-02-05",
  },
  {
    id: "stu_005",
    name: "Mateo Rodríguez",
    age: 8,
    grade: "3er grado",
    mode: "child",
    parentIds: ["parent_005"],
    teacherIds: ["teacher_001"],
    psychopedagogistId: "psych_001",
    enrolledAt: "2025-01-10",
  },
  {
    id: "stu_006",
    name: "Emma Martínez",
    age: 15,
    grade: "3er año",
    mode: "teen",
    parentIds: ["parent_006"],
    teacherIds: ["teacher_001"],
    psychopedagogistId: "psych_001",
    enrolledAt: "2025-02-10",
  },
]

export const mockKPIs: Record<string, StudentKPIs> = {
  stu_001: {
    studentId: "stu_001",
    period: "week",
    wpm: 45,
    wpmTrend: 12,
    accuracy: 68,
    accuracyTrend: -5,
    completionRate: 75,
    streak: 5,
    maxSpan: 4,
    hintsUsageRate: 35,
    totalExercises: 12,
    totalTime: 180,
    lastActive: "2025-01-20",
    level: 3,
  },
  stu_002: {
    studentId: "stu_002",
    period: "week",
    wpm: 85,
    wpmTrend: 8,
    accuracy: 82,
    accuracyTrend: 3,
    completionRate: 90,
    streak: 12,
    maxSpan: 6,
    hintsUsageRate: 15,
    totalExercises: 18,
    totalTime: 240,
    lastActive: "2025-01-20",
    level: 5,
  },
  stu_003: {
    studentId: "stu_003",
    period: "week",
    wpm: 52,
    wpmTrend: 5,
    accuracy: 78,
    accuracyTrend: 2,
    completionRate: 85,
    streak: 8,
    maxSpan: 5,
    hintsUsageRate: 22,
    totalExercises: 15,
    totalTime: 210,
    lastActive: "2025-01-20",
    level: 4,
  },
  stu_004: {
    studentId: "stu_004",
    period: "week",
    wpm: 72,
    wpmTrend: 10,
    accuracy: 88,
    accuracyTrend: 6,
    completionRate: 95,
    streak: 15,
    maxSpan: 7,
    hintsUsageRate: 12,
    totalExercises: 20,
    totalTime: 280,
    lastActive: "2025-01-20",
    level: 6,
  },
  stu_005: {
    studentId: "stu_005",
    period: "week",
    wpm: 38,
    wpmTrend: -3,
    accuracy: 55,
    accuracyTrend: -8,
    completionRate: 50,
    streak: 2,
    maxSpan: 3,
    hintsUsageRate: 45,
    totalExercises: 8,
    totalTime: 120,
    lastActive: "2025-01-19",
    level: 2,
  },
  stu_006: {
    studentId: "stu_006",
    period: "week",
    wpm: 95,
    wpmTrend: 15,
    accuracy: 92,
    accuracyTrend: 8,
    completionRate: 98,
    streak: 20,
    maxSpan: 8,
    hintsUsageRate: 8,
    totalExercises: 22,
    totalTime: 300,
    lastActive: "2025-01-20",
    level: 7,
  },
}

export const mockAlerts: Alert[] = [
  {
    id: "alert_001",
    studentId: "stu_001",
    type: "low_accuracy",
    level: "warning",
    title: "Precisión por debajo del 60%",
    message:
      "Martín ha tenido una precisión del 58% en las últimas 3 sesiones. Recomendamos activar más apoyo visual y practicar ejercicios de decodificación.",
    createdAt: "2025-01-19",
    notifiedRoles: ["parent", "teacher"],
    metadata: {
      metric: "accuracy",
      value: 58,
      threshold: 60,
      sessions: 3,
    },
  },
  {
    id: "alert_002",
    studentId: "stu_005",
    type: "low_accuracy",
    level: "critical",
    title: "Precisión crítica - Requiere intervención",
    message:
      "Mateo ha mostrado una precisión del 55% y baja tasa de finalización. Se recomienda una evaluación psicopedagógica y plan de intervención personalizado.",
    createdAt: "2025-01-18",
    notifiedRoles: ["parent", "teacher", "psychopedagogist"],
    metadata: {
      metric: "accuracy",
      value: 55,
      threshold: 60,
      sessions: 5,
    },
  },
  {
    id: "alert_003",
    studentId: "stu_005",
    type: "low_completion",
    level: "warning",
    title: "Baja tasa de finalización",
    message:
      "Mateo solo ha completado el 50% de los ejercicios asignados esta semana. Considerar ajustar la dificultad o aumentar la motivación.",
    createdAt: "2025-01-19",
    notifiedRoles: ["parent", "teacher"],
    metadata: {
      metric: "completionRate",
      value: 50,
      threshold: 70,
      sessions: 4,
    },
  },
]

export const mockInterventionPlan: InterventionPlan = {
  id: "plan_001",
  studentId: "stu_001",
  createdBy: "psych_001",
  createdAt: "2025-01-18",
  duration: 4,
  objectives: [
    "Mejorar precisión en decodificación silábica al 75%",
    "Aumentar velocidad lectora a 55 WPM",
    "Reducir uso de pistas al 25%",
  ],
  exercises: [
    {
      gameId: "rompe-y-une",
      frequency: "4x por semana",
      duration: 15,
    },
    {
      gameId: "lluvia-palabras",
      frequency: "3x por semana",
      duration: 10,
    },
  ],
  successCriteria: [
    "Precisión ≥75% en 5 sesiones consecutivas",
    "WPM ≥55 en ejercicios de nivel 3",
    "Completar 80% de ejercicios asignados",
  ],
  observations: [],
  status: "active",
}
