export interface GameInfo {
  id: string
  title: string
  description: string
  icon: string
  category: "reading" | "math" | "english"
  difficulty: "Fácil" | "Media" | "Difícil" | "Easy" | "Medium" | "Hard"
  skills: string[]
  adaptations: string[]
  ageGroup: "child" | "teen" | "both"
  duration: string
}

export const GAMES_CATALOG: GameInfo[] = [
  // JUEGOS DE LECTURA / DISLEXIA
  {
    id: "carrera-lectura",
    title: "Carrera de Lectura",
    description: "Avanza en la pista leyendo palabras y frases correctamente",
    icon: "flag",
    category: "reading",
    difficulty: "Media",
    skills: ["Lectura rápida", "Reconocimiento de palabras", "Fluidez lectora", "Comprensión inmediata"],
    adaptations: [
      "Progresión adaptativa (palabras → frases)",
      "Feedback visual inmediato",
      "Sin presión de tiempo",
      "Aleatorización Fisher-Yates",
      "Pistas opcionales",
    ],
    ageGroup: "both",
    duration: "5-8 min",
  },
  {
    id: "gauchos-reading",
    title: "Los Gauchos Argentinos",
    description: "Lectura y comprensión sobre la historia y cultura gaucha con preguntas evaluables",
    icon: "book-open",
    category: "reading",
    difficulty: "Media",
    skills: ["Comprensión lectora", "Vocabulario contextual", "Análisis de texto", "Cultura argentina"],
    adaptations: [
      "Dos modos adaptados por edad",
      "Párrafos cortos y espaciados",
      "Vocabulario con definiciones",
      "Feedback inmediato",
      "Indicador de progreso",
    ],
    ageGroup: "both",
    duration: "10-15 min",
  },
  {
    id: "busca-letra",
    title: "Busca la Letra",
    description: "Encuentra y selecciona la letra correcta entre varias opciones",
    icon: "search",
    category: "reading",
    difficulty: "Fácil",
    skills: ["Discriminación visual", "Reconocimiento de letras", "Atención selectiva"],
    adaptations: ["Fuente OpenDyslexic", "Alto contraste", "Tiempo ajustable", "Síntesis de voz"],
    ageGroup: "both",
    duration: "3-5 min",
  },
  {
    id: "rompe-y-une",
    title: "Rompe y Une",
    description: "Arrastra las sílabas para formar palabras completas",
    icon: "sparkles",
    category: "reading",
    difficulty: "Fácil",
    skills: ["Conciencia fonológica", "Segmentación silábica", "Formación de palabras"],
    adaptations: ["Drag & drop accesible", "Feedback auditivo", "Colores diferenciados"],
    ageGroup: "both",
    duration: "5-10 min",
  },
  {
    id: "lluvia-palabras",
    title: "Lluvia de Palabras",
    description: "Atrapa las palabras correctas que caen del cielo",
    icon: "zap",
    category: "reading",
    difficulty: "Media",
    skills: ["Velocidad de lectura", "Reconocimiento rápido", "Coordinación ojo-mano"],
    adaptations: ["Velocidad ajustable", "Tamaño de texto grande", "Pausas automáticas"],
    ageGroup: "both",
    duration: "3-5 min",
  },
  {
    id: "eco-palabras",
    title: "Eco de Palabras",
    description: "Escucha atentamente y escribe las palabras que oyes",
    icon: "star",
    category: "reading",
    difficulty: "Fácil",
    skills: ["Dictado", "Ortografía", "Memoria auditiva"],
    adaptations: ["Repetición ilimitada", "Control de velocidad", "Corrección progresiva"],
    ageGroup: "both",
    duration: "5-8 min",
  },
  {
    id: "historias-huecos",
    title: "Historias con Huecos",
    description: "Completa las historias eligiendo las palabras correctas",
    icon: "book-open",
    category: "reading",
    difficulty: "Media",
    skills: ["Comprensión lectora", "Vocabulario", "Contexto semántico"],
    adaptations: ["Opciones limitadas", "Pistas visuales", "Lectura en voz alta"],
    ageGroup: "both",
    duration: "8-12 min",
  },
  {
    id: "caza-errores",
    title: "Caza de Errores",
    description: "Encuentra y corrige errores ortográficos en textos",
    icon: "target",
    category: "reading",
    difficulty: "Media",
    skills: ["Ortografía", "Atención al detalle", "Revisión de textos"],
    adaptations: ["Resaltado de zonas", "Sugerencias contextuales", "Niveles progresivos"],
    ageGroup: "teen",
    duration: "7-10 min",
  },
  {
    id: "memotono",
    title: "Memotono",
    description: "Memoriza y reproduce secuencias de sonidos y palabras",
    icon: "music",
    category: "reading",
    difficulty: "Media",
    skills: ["Memoria auditiva", "Secuenciación", "Procesamiento fonológico"],
    adaptations: ["Secuencias cortas", "Repetición disponible", "Pistas rítmicas"],
    ageGroup: "both",
    duration: "5-7 min",
  },
  {
    id: "mision-lex-lumo",
    title: "Misión Lex & Lumo",
    description: "Ayuda a los personajes en una aventura de lectura",
    icon: "gamepad",
    category: "reading",
    difficulty: "Media",
    skills: ["Comprensión narrativa", "Toma de decisiones", "Vocabulario contextual"],
    adaptations: ["Narración completa", "Decisiones simplificadas", "Retroalimentación positiva"],
    ageGroup: "child",
    duration: "10-15 min",
  },
  {
    id: "tienda-lex",
    title: "Tienda de Lex",
    description: "Lee instrucciones y completa tareas de compra",
    icon: "shopping-bag",
    category: "reading",
    difficulty: "Fácil",
    skills: ["Lectura funcional", "Instrucciones", "Vocabulario cotidiano"],
    adaptations: ["Imágenes de apoyo", "Pasos simplificados", "Retroalimentación inmediata"],
    ageGroup: "child",
    duration: "5-8 min",
  },

  // JUEGOS DE MATEMÁTICAS / DISCALCULIA
  {
    id: "carrera-matematica",
    title: "Carrera de Matemática",
    description: "Resuelve operaciones matemáticas y llega a la meta",
    icon: "flag",
    category: "math",
    difficulty: "Media",
    skills: ["Cálculo mental", "Operaciones básicas", "Resolución de problemas", "Velocidad de cálculo"],
    adaptations: [
      "Progresión adaptativa (sumas → restas)",
      "Representación visual de números",
      "Sin presión de tiempo",
      "Aleatorización Fisher-Yates",
      "Pistas opcionales",
    ],
    ageGroup: "both",
    duration: "5-8 min",
  },
  {
    id: "super-sumador",
    title: "Super Sumador",
    description: "Resuelve sumas y restas con ayuda visual",
    icon: "calculator",
    category: "math",
    difficulty: "Fácil",
    skills: ["Operaciones básicas", "Cálculo mental", "Numeración"],
    adaptations: ["Representación visual", "Contador animado", "Verificación paso a paso"],
    ageGroup: "both",
    duration: "5-10 min",
  },
  {
    id: "cuenta-conmigo",
    title: "Cuenta Conmigo",
    description: "Cuenta objetos y aprende los números",
    icon: "hash",
    category: "math",
    difficulty: "Fácil",
    skills: ["Conteo", "Cardinalidad", "Correspondencia uno a uno"],
    adaptations: ["Objetos interactivos", "Conteo en voz alta", "Agrupación visual"],
    ageGroup: "child",
    duration: "3-5 min",
  },
  {
    id: "cual-es-mayor",
    title: "¿Cuál es Mayor?",
    description: "Compara números y cantidades",
    icon: "chevrons-up",
    category: "math",
    difficulty: "Fácil",
    skills: ["Comparación numérica", "Mayor/menor", "Magnitudes"],
    adaptations: ["Representación gráfica", "Línea numérica", "Símbolos claros"],
    ageGroup: "both",
    duration: "3-5 min",
  },
  {
    id: "cazador-numeros",
    title: "Cazador de Números",
    description: "Encuentra números en orden o según criterios",
    icon: "crosshair",
    category: "math",
    difficulty: "Media",
    skills: ["Secuenciación numérica", "Orden", "Reconocimiento de patrones"],
    adaptations: ["Pistas visuales", "Velocidad ajustable", "Rango personalizable"],
    ageGroup: "both",
    duration: "5-8 min",
  },

  // JUEGOS DE INGLÉS ADAPTADOS PARA DISLEXIA
  {
    id: "phonics-match",
    title: "Phonics Match",
    description: "Match English sounds with the correct words",
    icon: "volume-2",
    category: "english",
    difficulty: "Easy",
    skills: ["English phonics", "Sound-letter correspondence", "Pronunciation"],
    adaptations: ["Native audio", "Unlimited repeats", "Visual phoneme cues", "OpenDyslexic font"],
    ageGroup: "both",
    duration: "5-8 min",
  },
  {
    id: "picture-words",
    title: "Picture Words",
    description: "Spell English words by looking at pictures",
    icon: "image",
    category: "english",
    difficulty: "Easy",
    skills: ["English vocabulary", "Spelling", "Image-word association"],
    adaptations: ["Clear images", "Letter bank", "Audio pronunciation", "Progressive hints"],
    ageGroup: "both",
    duration: "5-10 min",
  },
  {
    id: "rhyme-time",
    title: "Rhyme Time",
    description: "Find words that rhyme in English",
    icon: "music",
    category: "english",
    difficulty: "Easy",
    skills: ["English phonological awareness", "Rhyming", "Word families"],
    adaptations: ["Audio support", "Visual grouping", "Simple word pairs", "Colorful feedback"],
    ageGroup: "both",
    duration: "5-7 min",
  },
  {
    id: "sight-words",
    title: "Sight Words Memory",
    description: "Practice common English words through memory games",
    icon: "eye",
    category: "english",
    difficulty: "Medium",
    skills: ["High-frequency English words", "Visual memory", "Reading fluency"],
    adaptations: ["Spaced repetition", "Multisensory", "Progress tracking", "Card size options"],
    ageGroup: "both",
    duration: "7-10 min",
  },
]

export function getGamesByCategory(category: "reading" | "math" | "english") {
  return GAMES_CATALOG.filter((game) => game.category === category)
}

export function getGamesByAgeGroup(ageGroup: "child" | "teen") {
  return GAMES_CATALOG.filter((game) => game.ageGroup === ageGroup || game.ageGroup === "both")
}

export function getGameById(id: string) {
  return GAMES_CATALOG.find((game) => game.id === id)
}
